### ISSUE TITLE
Suggestion "noTilde" option

### ISSUE THREAD

**Issue by fega** [sindresorhus/pretty-ms#32]
to avoid printing "~" in te beginning when you dont want it.

what do you think? I can send a PR.

**Comment by jimutt** [comment]
This would be a much appreciated feature

**Comment by milesj** [comment]
`prettyMs(time).replace('~', '')`?

**Comment by jimutt** [comment]
@milesj  Of course, that's [what I'm doing](https://github.com/jimutt/practice-log-app/blob/master/src/mixins/timeFilters.js), but it it feels like something that could fit as an option though.

**Comment by sindresorhus** [comment]
I don't think it's should be a separate option, since it only applies to the `compact` option. And `noTilde` is a bad option name as it's a double-negative. 

I'm just wondering whether we should either remove the tilde by default or change the `compact` option to also accept: `{compact: 'no-tilde'}`.

**Comment by fega** [comment]
@sindresorhus I like the idea of remove the tilde.

**Comment by jimutt** [comment]
Yes, removed by default seems most reasonable to me. I'd rather let the user add it manually if needed. I can think of many contexts where an automatically added tilde is unwanted/makes little sense formatting wise. But if you'd like to keep the funcitonality whithin the library I personally think that it'd be more suitable as an opt-in, through the options object, rather than opt-out. Though that would mean a major version bump, so perhaps `{compact: 'no-tilde'}` is a better alternative if you want to avoid that.

**Comment by sindresorhus** [comment]
Alright. Let's just remove if. If someone complains we can consider adding a `no-tilde` option value.
